// Örnek veri

export const remarks = [
  {
    projeAdi: "NB001",
    tipi: "Klass", // Klass, Departman, Armatör
    konusu: "Dizayn", // Dizayn, Planlama, İç Satınalma, Teknik Satınalma, Atölye, Üretim Çelik, Boru, Üretim Elektrik, Üretim Teçhizat, Yaşam Mahali, Departman, İş Güvenliği
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet", // Ahmet, Mehmet, Niyazi
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Yayınlanmış", // Yazılmış, Yayınlanmış, Atanmış, İşleme Alınmış, Red Edilmiş, Tamamlanmış, Toplam
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Planlama",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Mehmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Yazılmış",
  },
  {
    projeAdi: "NB002",
    tipi: "Armatör",
    konusu: "Atölye",
    numarasi: "NB001-Armatör-001",
    yoneticisi: "Niyazi",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "11.02.2024",
    ekDosya: "",
    durum: "Yayınlanmış",
  },
  {
    projeAdi: "NB003",
    tipi: "Klass",
    konusu: "Boru",
    numarasi: "NB001-Klass-002",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "14.02.2024",
    ekDosya: "",
    durum: "Atanmış",
  },
  {
    projeAdi: "NB004",
    tipi: "Armatör",
    konusu: "Dizayn",
    numarasi: "NB001-Armatör-002",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "18.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB005",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-003",
    yoneticisi: "Mehmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB006",
    tipi: "Armatör",
    konusu: "Teknik Satınalma",
    numarasi: "NB001-Armatör-003",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB007",
    tipi: "Klass",
    konusu: "Planlama",
    numarasi: "NB001-Klass-004",
    yoneticisi: "Mehmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB008",
    tipi: "Klass",
    konusu: "Teknik Satınalma",
    numarasi: "NB001-Klass-005",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB009",
    tipi: "Armatör",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-005",
    yoneticisi: "Mehmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB0010",
    tipi: "Klass",
    konusu: "Teknik Satınalma",
    numarasi: "NB001-Klass-006",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB0011",
    tipi: "Armatör",
    konusu: "Dizayn",
    numarasi: "NB001-Armatör-006",
    yoneticisi: "Mehmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB0012",
    tipi: "Armatör",
    konusu: "Planlama",
    numarasi: "NB001-Armatör-0012",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB0013",
    tipi: "Klass",
    konusu: "Planlama",
    numarasi: "NB001-Klass-0013",
    yoneticisi: "Mehmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
];

export const projects = [
  {
    projeAdi: "NB001",
    yazilmis: 2,
    yayinlanmis: 4,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 6,
    tamamlanmis: 7,
    toplam: 28,
  },
  {
    projeAdi: "NB002",
    yazilmis: 2,
    yayinlanmis: 6,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 3,
    tamamlanmis: 8,
    toplam: 28,
  },
  {
    projeAdi: "NB003",
    yazilmis: 2,
    yayinlanmis: 5,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 3,
    tamamlanmis: 7,
    toplam: 28,
  },
  {
    projeAdi: "NB004",
    yazilmis: 2,
    yayinlanmis: 5,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 3,
    tamamlanmis: 7,
    toplam: 28,
  },
  {
    projeAdi: "NB005",
    yazilmis: 2,
    yayinlanmis: 5,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 3,
    tamamlanmis: 7,
    toplam: 28,
  },
  {
    projeAdi: "NB006",
    yazilmis: 2,
    yayinlanmis: 5,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 3,
    tamamlanmis: 7,
    toplam: 28,
  },
  {
    projeAdi: "NB0078",
    yazilmis: 2,
    yayinlanmis: 5,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 3,
    tamamlanmis: 7,
    toplam: 28,
  },
  {
    projeAdi: "NB0097",
    yazilmis: 2,
    yayinlanmis: 5,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 3,
    tamamlanmis: 7,
    toplam: 28,
  },
];
