export const remarks = [
  {
    projeAdi: "NB001",
    tipi: "Klass", // Klass, Departman, Armatör
    konusu: "Dizayn", // Dizayn, Planlama, İç Satınalma, Teknik Satınalma, Atölye, Üretim Çelik, Boru, Üretim Elektrik, Üretim Teçhizat, Yaşam Mahali, Departman, İş Güvenliği
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet", // Ahmet, Mehmet, Niyazi
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Yayınlanmış", // Yazılmış, Yayınlanmış, Atanmış, İşleme Alınmış, Red Edilmiş, Tamamlanmış, Toplam
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
  {
    projeAdi: "NB001",
    tipi: "Klass",
    konusu: "Dizayn",
    numarasi: "NB001-Klass-001",
    yoneticisi: "Ahmet",
    yazari: "Mike",
    basligi: "Fire Safety",
    aciklama: "Güncellenmeli",
    olusturulmaTarihi: "10.01.2024",
    hedefTarih: "10.02.2024",
    ekDosya: "",
    durum: "Tamamlanmış",
  },
];

export const projects = [
  {
    projeAdi: "NB001",
    yazilmis: 2,
    yayinlanmis: 4,
    atanmis: 4,
    islemeAlinmis: 5,
    redEdilmis: 6,
    tamamlanmis: 7,
    toplam: 28,
  },
];
